{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cvtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cvTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cvTools/cvTools_{{ version }}.tar.gz
  sha256: 14c31a7aab0cf9bba2a5d0ed79d8c942152a349dee32e25d912df89a2590346f

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-lattice
    - r-robustbase
  run:
    - r-base
    - r-lattice
    - r-robustbase

test:
  commands:
    - $R -e "library('cvTools')"           # [not win]
    - "\"%R%\" -e \"library('cvTools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=cvTools
  license: GPL-2.0-or-later
  summary: Tools that allow developers to write functions for cross-validation with minimal programming effort and assist users with model selection.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
