{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cvtools
  version: {{ version|replace("-", "_") }}

source:
  fn: cvTools_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/cvTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cvTools/cvTools_{{ version }}.tar.gz
  sha256: 520f0b194444d918440e971b16ad4e8579f953dd6d39ffc5f87b61589b59fd2c

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-lattice
    - r-robustbase
  run:
    - r-base
    - r-lattice
    - r-robustbase

test:
  commands:
    - $R -e "library('cvTools')"           # [not win]
    - "\"%R%\" -e \"library('cvTools')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=cvTools
  license: GPL (>= 2)
  summary: Tools that allow developers to write functions for cross-validation with minimal programming
    effort and assist users with model selection.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
