appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: vmZa2vb5O9WYcAJa+D50b8T743RRwwParXk8HxumZ3Df3RS3W6LyGbORThrnEEbDEMgOL/utaKA1eaRvX6sm3+oVQ4Efa2rXNi7o+42HHG+2gNOBnLmDLuWAzr6YGzKWg316Z9Ijafg7cfLUM5iSe38/S+psq+dcbavBNJ15gnGHsC60clnMMaqX5Y7KoK3ydumlZggbI7sanNohi+Eaf6IzcyYZv5BWLdOUTkg0MuEHxkqduztjsfm/nrk0qQyVkcq0Kg/lyMbTzMTx4c20KDtrh/I+6j/A+u8fhZ6nXmKJ7USmwi4M98icJTo3UCdXjE6YLOUlFp2bOt8UN3m1fMIC43RS7VNsCUDqRaFIlH994dLGKRO5EkkCb2srrTxkEGa4hMr/+Jx/RmOyGZ8wOqAmQLygCpKLkFLKbNnmDASLkyWWFcbTMuZTOZwWovvW1H+HckyQSSyIp7KRebYNKsSI+SzAWLb2NmW1X1YDu6khByjF0DlsXpB+W+lxOWEn5ThhkKhrUF0o/S611rveDrs+kvnvhrBfw6gyAHL0MoinQZ8+6eXiClyBR9WxfzH16zcVc5H/Fv9D9ktEj+eNgGZ8VzGQOdtQiHHf3AGH5m71lH8wFpYMgqMkkgrrk9fC6WWN2CJ7E2EuzZK4zTE+xuU2aDR9cZrXzqflwvfDFH8=}
bot:
  automerge: true
